version: 10.1.5
os: Visual Studio 2015
environment:
  solution_path: RNGReporter.sln
pull_requests:
  do_not_increment_build_number: true
artifacts:
  - path: RNGReporter.zip
    name: RNGReporter
build:
  project: $(solution_path)
  verbosity: minimal
after_build:
  - ps: 7z a RNGReporter.zip .\RNGReporter\bin\Debug\RNGReporter.exe